  stages:
    - test
    - build

  run_tests:
    stage: tests
    image: python:3.8.9
    before-script:
      - sudo pip3 install --upgrade pip && pip3 install -U pytest
    script:
      - pytest --cov

  build_image:
    stage: build
    image: docker:23.0.0-rc.3
    services:
      - docker:23.0.0-rc.3-dind
    variables:
      DOCKER_TLS_CERTDIR: "/certs"
    before_script:
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    script: 
      - docker build -t app_image -f docker/Dockerfile .
      - docker push app_image