version: '3'

services:
    app:
        build:
            dockerfile: docker/Dockerfile
            context: .
        depends_on:
            - db
        environment:
            DB_HOST: db
        volumes:
            - ./src:/src
            #- ./migrations:/app/migrations
        ports:
            - 8000:8000

    db:
        image: mongo:latest
        ports:
            - 5432:27017
        volumes:
            - /data:/data
        environment:
            MONGO_USER: lapis
            MONGO_PASSWORD: lapis
            MONGO_DB: app