version: '3'

services:

    my-mongo-dev:
        container_name: my-mongo-dev
        image: mongo:latest
        command: mongod --port 27017
        ports:
            - 5432:27017
        volumes:
            - /my-mongo-dev-deb-data:/data/db